-- MYSQL ASSIGNMENT 1
-- DDL COMMANDS & CONSTRAINS



SHOW DATABASES;
DROP DATABASE IF EXISTS EMPLOYEE;
-- PART 1 : DATABSE AND TABLE CREATION


CREATE DATABASE EMPLOYEE;
USE EMPLOYEE;

CREATE TABLE DEPARTMENTS (
DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(100) NOT NULL UNIQUE
);
DESC DEPARTMENTS;

CREATE TABLE LOCATION (
LOCATION_ID INT,
LOCATION VARCHAR(50)
);

SHOW TABLES;

CREATE TABLE EMPLOYEES(
EMPLOYEE_ID INT,
EMPLOYEE_NAME VARCHAR(50),
GENDER ENUM("M","F"),
AGE INT,
HIRE_DATE DATE,
DESIGNATION VARCHAR(100),
department_id int,
location_id int,salary decimal(10,2)
);

desc employees;

--  PART 2:ALTER TABLE
alter table employees
add column email varchar(100);

desc employees;

alter table employees
modify column designation
varchar(200);

desc employees;

alter table employees
drop column age;
-- PART 3: TABLE RENAMING

ALTER TABLE EMPLOYEES
RENAME COLUMN HIRE_DATE TO DATE_OF_JOINING;

rename  table departments to DEPARTMENTS_INFO;

RENAME TABLE LOCATION TO LOCATIONS;

SHOW TABLES;

-- PART4: TRUNCATE

TRUNCATE TABLE EMPLOYEES;

SHOW TABLES;

-- PART 5: DROP

DROP TABLE EMPLOYEES;

SHOW TABLES;

DROP DATABASE EMPLOYEE;

-- PART 6: CONSTRAINTS

CREATE DATABASE EMPLOYEE;

USE EMPLOYEE;

CREATE TABLE DEPARTMENTS (
DEPARTMENT_ID INT PRIMARY KEY,
DEPARTMENT_NAME VARCHAR(100) NOT NULL UNIQUE);

DESC DEPARTMENTS;

-- PART 8 : CONSTRAINTS TESTING

INSERT INTO DEPARTMENTS VALUES
(1,"SALES"),
(2,"HR"),
(3,"FINANCE");

SELECT * FROM DEPARTMENTS;
INSERT INTO DEPARTMENTS
VALUES(4,"HR");
INSERT INTO DEPARTMENTS;
VALUES(5, NULL);

CREATE TABLE LOCATION (
LOCATION_ID INT AUTO_INCREMENT PRIMARY KEY,
LOCATION VARCHAR(50) NOT NULL UNIQUE
);

DESC LOCATION;

INSERT INTO LOCATION (LOCATION)
VALUES("KOCHI");
SELECT * FROM LOCATION;
INSERT INTO LOCATION (LOCATION)
VALUES("KOLLAM");
INSERT INTO LOCATION (LOCATION)
VALUES("KOLLAM");
INSERT INTO LOCATION (LOCATION)
VALUES("NULL");
SELECT * FROM LOCATION;
DELETE FROM LOCATION 
WHERE LOCATION_ID =4;
SELECT* FROM LOCATION;
INSERT INTO LOCATION (LOCATION)
VALUES(NULL);

CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50)
NOT NULL,
GENDER ENUM("M","F"),
AGE INT CHECK (AGE >=18),
HIRE_DATE DATE DEFAULT(CURRENT_DATE),
DESIGNATION VARCHAR(100),
DEPARTMENT_ID INT,
LOCATION_ID INT,
SALARY DECIMAL(10,2),
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES
DEPARTMENTS(DEPARTMENT_ID),
FOREIGN KEY(LOCATION_ID)
REFERENCES LOCATION(LOCATION_ID)
);

USE EMPLOYEE;

SHOW TABLES;

CREATE TABLE EMPLOYEES (
EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50)
NOT NULL,
GENDER ENUM("M","F"),
AGE INT CHECK (AGE >=18),
HIRE_DATE DATE DEFAULT(CURRENT_DATE),
DESIGNATION VARCHAR(100),
DEPARTMENT_ID INT,
LOCATION_ID INT,
SALARY DECIMAL(10,2),
FOREIGN KEY (DEPARTMENT_ID)
REFERENCES
DEPARTMENTS(DEPARTMENT_ID),
FOREIGN KEY(LOCATION_ID)
REFERENCES LOCATION(LOCATION_ID)
);
SHOW TABLES;
DESC EMPLOYEES;
DESC EMPLOYEES;

SHOW CREATE TABLE EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;

USE EMPLOYEE;
SHOW TABLES;
DESC DEPARTMENTS;
DESC LOCATION;
DESC EMPLOYEES;                

INSERT INTO EMPLOYEES 
(EMPLOYEE_id,EMPLOYEE_NAME,GENDER,AGE,DESIGNATION,DEPARTMENT_ID,LOCATION_ID,SALARY)
VALUES
(1,"ABHI","M",23,"DATA ANALYST",1,1,30000);
INSERT INTO EMPLOYEES 
(EMPLOYEE_id,EMPLOYEE_NAME,GENDER,AGE,DESIGNATION,DEPARTMENT_ID,LOCATION_ID,SALARY)
VALUES
(1,"ABHAY","M",24,"DEVELOPER",1,1,33000);
INSERT INTO EMPLOYEES 
(EMPLOYEE_id,EMPLOYEE_NAME,GENDER,AGE,DESIGNATION,DEPARTMENT_ID,LOCATION_ID,SALARY)
VALUES
(2,NULL,"M",24,"DEVELOPER",1,1,33000);
INSERT INTO EMPLOYEES 
(EMPLOYEE_id,EMPLOYEE_NAME,GENDER,AGE,DESIGNATION,DEPARTMENT_ID,LOCATION_ID,SALARY)
VALUES
(2,"ABHAY","X",24,"DEVELOPER",1,1,33000);
INSERT INTO EMPLOYEES 
(EMPLOYEE_id,EMPLOYEE_NAME,GENDER,AGE,DESIGNATION,DEPARTMENT_ID,LOCATION_ID,SALARY)
VALUES
(5,"ABHAY","M",14,"DEVELOPER",1,1,33000);
INSERT INTO EMPLOYEES 
(EMPLOYEE_id,EMPLOYEE_NAME,GENDER,AGE,DESIGNATION,DEPARTMENT_ID,LOCATION_ID,SALARY)
VALUES
(2,"ABHAY","M",26,"DEVELOPER",1,1,33000);
SELECT * FROM EMPLOYEES;

USE EMPLOYEE;
SELECT DATABASE();
SHOW TABLES;
DESC DEPARTMENTS;
DESC LOCATION;
DESC EMPLOYEES;
SELECT * FROM EMPLOYEES;
SHOW CREATE TABLE EMPLOYEES;
SELECT * FROM location;
SELECT * FROM departments;                                    
SELECT * FROM EMPLOYEES;
show tables;      
DELETE from employees;

set sql_safe_updates =0;
DELETE from location;
DELETE from departments;
set sql_safe_updates =1;
INSERT INTO departments (department_id, department_name) VALUES
(1, 'Software Development'),
(2, 'Marketing'),
(3, 'Data Science'),
(4, 'Human Resources'),
(5, 'Product Management'),
(6, 'Content Creation'),
(7, 'Finance'),
(8, 'Design'),
(9, 'Research and Development'),
(10, 'Customer Support'),
(11, 'Business Development'),
(12, 'IT'),
(13, 'Operations');

INSERT INTO location (location) VALUES
('Chennai'),
('Bangalore'),
('Hyderabad'),
('Pune');

INSERT INTO employees (employee_id, employee_name, gender, age, hire_date, designation, department_id, location_id, salary) VALUES
(5001, 'Vihaan Singh', 'M', 27, '2015-01-20', 'Data Analyst', 3, 4, 60000),
(5002, 'Reyansh Singh', 'M', 31, '2015-03-10', 'Network Engineer', 12, 1, 80000),
(5003, 'Aaradhya Iyer', 'F', 26, '2015-05-20', 'Customer Support Executive', 10, 2, 45000),
(5004, 'Kiara Malhotra', 'F', 29, '2015-07-05', NULL, 8, 3, 70000),
(5005, 'Anvi Chaudhary', 'F', 25, '2015-09-11', 'Business Development Executive', 11, 1, 55000),
(5006, 'Dhruv Shetty', 'M', 28, '2015-11-20', 'UI Developer', 8, 2, 65000),
(5007, 'Anushka Singh', 'F', 32, '2016-01-15', 'Marketing Manager', 2, 3, 90000),
(5008, 'Diya Jha', 'F', 27, '2016-03-05', 'Graphic Designer', 8, 4, 70000),
(5009, 'Kiaan Desai', 'M', 30, '2016-05-20', 'Sales Executive', 11, 3, 55000),
(5010, 'Atharv Yadav', 'M', 29, '2016-07-10', 'Systems Administrator', 12, 4, 80000),
(5011, 'Saanvi Patel', 'F', 28, '2016-09-20', 'Marketing Analyst', 2, 1, 60000),
(5012, 'Myra Verma', 'F', 26, '2016-11-05', 'Operations Manager', 13, 2, 95000),
(5013, 'Arnav Rao', 'M', 33, '2017-01-20', 'Customer Success Manager', 10, 3, 75000),
(5014, 'Vihaan Mohan', 'M', 30, '2017-03-10', 'Supply Chain Analyst', 10, 2, 60000),
(5015, 'Ishaan Kumar', 'M', 27, '2017-05-20', 'Financial Analyst', 7, 1, 85000),
(5016, 'Zoya Khan', 'F', 31, '2017-07-05', 'Legal Counsel', 4, 4, 100000),
(5017, 'Kabir Nair', 'M', 28, '2017-09-11', 'IT Support Specialist', 12, 2, 80000),
(5018, 'Ishan Mishra', 'M', 25, '2017-11-20', 'Research Scientist', 9, 3, 75000),
(5019, 'Ishika Patel', 'F', 29, '2018-01-15', 'Talent Acquisition Specialist', 4, 4, 55000),
(5020, 'Aarav Nair', 'M', 32, '2018-03-05', 'Software Engineer', 1, 1, 90000),
(5021, 'Advik Kapoor', 'M', 26, '2018-05-20', 'Finance Analyst', 7, 3, 85000),
(5022, 'Aadhya Iyengar', 'F', 28, '2018-07-10', 'HR Specialist', 4, 4, 60000),
(5023, 'Anika Paul', 'F', 30, '2018-09-20', 'Public Relations Specialist', 2, 2, 70000),
(5024, 'Aryan Shetty', 'M', 27, '2018-11-05', 'Product Manager', 5, 1, 95000),
(5025, 'Avni Iyengar', 'F', 31, '2019-01-20', 'Data Scientist', 3, 4, 100000),
(5026, 'Vivaan Singh', 'M', 29, '2019-03-10', 'Business Analyst', 3, 2, 75000),
(5027, 'Ananya Paul', 'F', 32, '2019-05-20', 'Content Writer', 6, 3, 60000),
(5028, 'Anaya Kapoor', 'F', 26, '2019-07-05', 'Event Coordinator', 6, 1, 60000),
(5029, 'Arjun Kumar', 'M', 33, '2019-09-11', 'Quality Assurance Analyst', 12, 2, 80000),
(5030, 'Sara Iyer', 'F', 28, '2019-11-20', 'Project Manager', 5, 1, 90000);

SELECT * FROM location;
SELECT * FROM departments;                                    
SELECT * FROM EMPLOYEES;
DELETE from location;


alter TABLE LOCATION
AUTO_INCREMENT =1;

INSERT INTO location (location) VALUES
('Chennai'),
('Bangalore'),
('Hyderabad'),
('Pune');

-- DISTINCT 
SELECT DISTINCT SALARY FROM EMPLOYEES;

-- Alias (AS):
SELECT AGE AS EMPLOYEE_AGE,
		SALARY AS EMPLOYEE_SALARY
        FROM employees;
        
        -- Where Clause & Operators:
        
        SELECT * FROM EMPLOYEES
        WHERE SALARY > 50000 AND
        HIRE_DATE < "2016-01-01";
        
        UPDATE EMPLOYEES
        SET DESIGNATION = "DATA_SCIENTIST"
        WHERE DESIGNATION IS NULL;

-- Sorting and Grouping Data:
-- 1. ORDER BY:
SELECT * FROM EMPLOYEES
 ORDER BY DEPARTMENT_ID ASC,
 SALARY DESC;
 
 -- 2. LIMIT:
 SELECT * FROM employees
 WHERE HIRE_DATE >="2018-01-01"
 AND HIRE_DATE <"2019-01-01"
 ORDER BY HIRE_DATE ASC
 LIMIT 5;
 
 -- 3. Aggregate Functions:
 SELECT SUM(SALARY) AS TOTAL_FINANCIAL_SALARY 
 FROM employees
 WHERE DEPARTMENT_ID = 7;
 
 SELECT MIN(AGE) AS MIN_AGE
 FROM EMPLOYEES;        
 
 -- 4. GROUP BY:
 SELECT LOCATION_ID,MAX(SALARY) AS MAX_SALARY
 FROM EMPLOYEES
 GROUP BY LOCATION_ID;
 
 SELECT DESIGNATION , AVG(SALARY) AS AVG_SALARY
 FROM EMPLOYEES
 WHERE DESIGNATION LIKE "%ANALYST"
 GROUP BY DESIGNATION;
 
 -- 5. HAVING:
 SELECT DEPARTMENT_ID,COUNT(*) AS EMPLOYEE_COUNT
 FROM EMPLOYEES
 GROUP BY DEPARTMENT_ID
 HAVING COUNT(*) <3;
 
 SELECT LOCATION_ID,AVG(AGE) AS AVG_AGE
 FROM EMPLOYEES
 WHERE GENDER = "F"
 GROUP BY LOCATION_ID
 HAVING avg(AGE)<30;

 -- Joins: 
-- 1. Inner Join: 
 SELECT E.EMPLOYEE_NAME,
		E.DESIGNATION,
		D.DEPARTMENT_NAME
        FROM EMPLOYEES E
        INNER JOIN DEPARTMENTS D  ON
        E.DEPARTMENT_ID = D.DEPARTMENT_ID;
        
        -- 2. Left Join:
        SELECT 
        D.DEPARTMENT_ID,D.DEPARTMENT_NAME,
        COUNT(E.EMPLOYEE_ID) AS EMPLOYEE_COUNT
        FROM DEPARTMENTS D 
        LEFT JOIN EMPLOYEES E ON D.DEPARTMENT_ID =
        E.DEPARTMENT_ID
        GROUP BY D.DEPARTMENT_ID,
        D.DEPARTMENT_NAME;
        
        -- 3. Right Join: 
 SELECT 
 L.LOCATION,
 E.EMPLOYEE_NAME
 FROM EMPLOYEES E
 RIGHT JOIN LOCATION L 
 ON E.LOCATION_ID = L.LOCATION_ID;
 